[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ginza==5.2.0",
    "ja-ginza==5.2.0",
    "numpy==1.26.4",
    "spacy==3.7.5",
]

[dependency-groups]
dev = [
    "ruff>=0.9.3",
]
