name: OpenAPI Drift Check

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  drift-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install "fastapi>=0.104.0" "pydantic>=2.0.0"

      - name: Generate OpenAPI JSON
        env:
          PYTHONPATH: .
        run: |
          python backend/scripts/export_openapi.py --out docs/api/openapi.generated.json

      - name: Ensure reference exists
        run: |
          test -f docs/api/openapi.v1.json || { echo "::error file=docs/api/openapi.v1.json::Missing reference OpenAPI. Run scripts/export_openapi.py and commit docs/api/openapi.v1.json"; exit 1; }

      - name: Check drift
        run: |
          diff -u docs/api/openapi.v1.json docs/api/openapi.generated.json || { echo "::error::OpenAPI drift detected. Regenerate and commit docs/api/openapi.v1.json"; exit 1; }

      - name: Upload generated OpenAPI (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: openapi-generated
          path: docs/api/openapi.generated.json
